# Generated by Django 5.2.1 on 2025-07-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='City',
            field=models.CharField(default='تهران', max_length=50),
        ),
    ]
